# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-15 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='code',
            field=models.CharField(default=123132, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='quiz',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='slug',
        ),
    ]
