# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-20 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_option_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('TEXT', 'text'), ('NUMBER', 'number'), ('SCORE', 'score'), ('OPTION', 'option'), ('OPTIONS', 'many options'), ('ORDER', ' order')], default='TEXT', max_length=7),
        ),
    ]
