# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quizstats_answers_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizstats',
            name='level_up_time',
        ),
    ]
