# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-26 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typers', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_sponsor',
            field=models.BooleanField(default=False),
        ),
    ]
