# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-24 01:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('typers', '0004_auto_20170723_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sender_friendships', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
