# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typers', '0006_match_advertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_notification',
            field=models.BooleanField(default=False),
        ),
    ]
