# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 20:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('typers', '0007_profile_has_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistics', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='typers.Round')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typers.Tournament')),
            ],
        ),
    ]
