# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('typers', '0008_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='round',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='typers.Round'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='ranking',
            unique_together=set([('tournament', 'round')]),
        ),
    ]
