# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('typers', '0009_auto_20170824_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ranking',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
