# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typers', '0010_auto_20170824_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='advertise',
            field=models.BooleanField(default=False),
        ),
    ]
