# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typers', '0011_ranking_advertise'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ranking',
            new_name='RoundRanking',
        ),
    ]
