# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 17:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('typers', '0012_auto_20170827_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertise', models.BooleanField(default=False)),
                ('statistics', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typers.Tournament')),
            ],
        ),
    ]
