# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typers', '0013_tournamentranking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='active',
        ),
    ]
