# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 21:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('typers', '0015_tournament_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prize',
            name='position',
        ),
        migrations.RemoveField(
            model_name='prize',
            name='winner',
        ),
        migrations.AddField(
            model_name='prize',
            name='winner',
            field=models.ManyToManyField(related_name='winner_prizes', to=settings.AUTH_USER_MODEL),
        ),
    ]
