# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typers', '0016_auto_20171020_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='info',
            field=models.CharField(blank=True, max_length=1048, null=True),
        ),
    ]
