# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-28 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typers', '0017_prize_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
