# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-28 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typers', '0018_auto_20171228_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prize',
            name='winner',
        ),
    ]
