# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-28 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typers', '0019_remove_prize_winner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prize',
            unique_together=set([('name', 'order_number', 'tournament', 'round')]),
        ),
    ]
