# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-30 13:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('typers', '0020_auto_20171228_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistics', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typers.Match')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typers.Tournament')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='matchstatistics',
            unique_together=set([('match', 'tournament')]),
        ),
    ]
