# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-30 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typers', '0022_remove_match_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_quiz_organizer',
            field=models.BooleanField(default=True),
        ),
    ]
